### ISSUE TITLE
The Google Drive link to the dataset is no longer working

### ISSUE THREAD

**Issue by ZhangQ714** [JHLee0513/semantic_bevnet#5]
Hello, author. I would like to run your code, but the dataset link is no longer working. Would you have time to restore it?

**Comment by ZhangQ714** [comment]
@JHLee0513

**Comment by JHLee0513** [comment]
We no longer have the google drive folder available unfortunately, you will have to refer to dataset generation at https://github.com/JHLee0513/semantic_bevnet/tree/main/generate_bev_gt
